[theme]
primaryColor = "#157F74"
backgroundColor = "#F7F9F8"
secondaryBackgroundColor = "#EDF2F0"
textColor = "#182C29"
font = "sans serif"

[server]
address = "127.0.0.1"
headless = true
maxUploadSize = 500

[browser]
gatherUsageStats = false
